name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: fraude_detection_system_env
          environment-file: '${{ github.workspace }}/project_env/fraude_detection_system_env.yaml'

      - name: Install Dependencies
        run: |
          conda install --yes --file "/Users/sabri/Desktop/Study /Youcode/Github/Sprint_4/fraud-detection-system/requirements.txt"

      - name: Run Tests
        run: |
          python -m pytest

      - name: Lint Code
        run: |
          pylint fraud-detection-system
